name: Java CI

on:
  push:
    branches:
      - '*/*'
      - '**/*'
      - '*'
      - '!release/*'

#################   Build Overview #################
#
#  The Build Process is:
#  1.  Checkout project
#  2.  Install and Deploy the BOM POMs
#  3.  Run tests on Mac and Linux
#  4.  Complete build and run on Linux
#  5.  Deploy from Linux but not Mac (avoid conflicts)
#
#################   Set up Environment  #################

env:
  BUILD_ENVIRONMENT: github

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      #################   Checkout #################
      #
      #   This step checks out the project
      #
      #################   Checkout #################

    - name: Checkout
      uses: actions/checkout@v1

      #################   JDK  #################
      #
      #     Use JDK 11 to build
      #
      #################   JDK  #################

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 17


      #################   Install and Deploy  #################
      #
      #   We're going to deploy the BOM from Ubuntu only
      #   The BOM will be consumed by subsequent test-runs on Ubuntu, Windows, and MacOS
      #
      #################   Install and Deploy  #################

    - name: Install and Deploy Maven POMs
      if: matrix.platform == 'ubuntu-latest'
      run: >-
        mvn install deploy -f bom
        --settings bom/settings/settings.xml
        -Dmaven-repo.github.username=${{secrets.MAVEN_REPOSITORY_USERNAME}}
        -Dmaven-repo.github.password=${{secrets.MAVEN_REPOSITORY_PASSWORD}}

      #################   Install BOMs  #################
      #
      #   We're going to install the BOM POMs to the local maven repository
      #   The BOM will be consumed by subsequent test-runs on Ubuntu, Windows, and MacOS
      #
      #################   Install BOMs  #################
    - name: Install Maven POMs
      run: mvn install -f bom --settings bom/settings/settings.xml "-Dmaven-repo.github.username=${{secrets.MAVEN_REPOSITORY_USERNAME}}" "-Dmaven-repo.github.password=${{secrets.MAVEN_REPOSITORY_PASSWORD}}"


      #################   Test  #################
      #
      #   Now that the BOM is deployed, lets
      #   run all the tests on all the platforms
      #   for completeness
      #
      #################   Test  #################


    - name: Test on All Platforms
      uses: eskatos/gradle-command-action@v1
      env:
        JAVA_TOOL_OPTIONS: -Duser.language=en -Duser.country=US
      with:
        gradle-version: 7.4
        arguments: >-
          assemble build sA -i
          -PmavenRepositoryUsername=${{secrets.MAVEN_REPOSITORY_USERNAME}}
          -PmavenRepositoryPassword=${{secrets.MAVEN_REPOSITORY_PASSWORD}}
          -PmavenRepositoryUrl=${{secrets.MAVEN_REPOSITORY_URL}}
          --stacktrace --max-workers=1

      #################   Test  #################
      #
      #   Run tests on all Maven Platforms
      #   TODO: only Linux is supported
      #
      #################   Test  #################


    - name: Test Maven Plugin on All Platforms
      if: matrix.os == 'ubuntu-latest'
      run: >-
        mvn deploy -f tools/zephyr-maven-plugin
        --settings bom/settings/settings.xml
        -Dmaven-repo.github.username=${{secrets.MAVEN_REPOSITORY_USERNAME}}
        -Dmaven-repo.github.password=${{secrets.MAVEN_REPOSITORY_PASSWORD}}


      #################   Test  #################
      #
      #   Run tests on all Maven Platforms
      #
      #################   Test  #################

    - name: Build with Gradle
      uses: eskatos/gradle-command-action@v1
      env:
        JAVA_TOOL_OPTIONS: -Duser.language=en -Duser.country=US
      with:
        gradle-version: 7.4
        arguments: >-
          assemble build sA
          -i -PmavenRepositoryUsername=${{secrets.MAVEN_REPOSITORY_USERNAME}}
          -PmavenRepositoryPassword=${{secrets.MAVEN_REPOSITORY_PASSWORD}}
          -PmavenRepositoryUrl=${{secrets.MAVEN_REPOSITORY_URL}}
          --stacktrace
          --max-workers=1


      #################   Deploy  #################
      #
      # Assuming the tests have passed, deploy from
      # Ubuntu only
      #
      #################   Deploy   #################

    - name: Deploy Artifacts
      uses: eskatos/gradle-command-action@v1
      if: matrix.platform == 'ubuntu-latest'
      env:
        JAVA_TOOL_OPTIONS: -Duser.language=en -Duser.country=US
      with:
        gradle-version: 7.4
        arguments: >-
          assemble build publish sA -i
          -PmavenRepositoryUsername=${{secrets.MAVEN_REPOSITORY_USERNAME}}
          -PmavenRepositoryPassword=${{secrets.MAVEN_REPOSITORY_PASSWORD}}
          -PmavenRepositoryUrl=${{secrets.MAVEN_REPOSITORY_URL}}
          --stacktrace --max-workers=1
